//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Havamal.Resources.TextResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Havamal.Resources.TextResources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search in all versions.
        /// </summary>
        internal static string AllLang {
            get {
                return ResourceManager.GetString("AllLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Language.
        /// </summary>
        internal static string AppLang {
            get {
                return ResourceManager.GetString("AppLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare.
        /// </summary>
        internal static string Compare {
            get {
                return ResourceManager.GetString("Compare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load favorites.
        /// </summary>
        internal static string CouldNotLoadFavs {
            get {
                return ResourceManager.GetString("CouldNotLoadFavs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load verses for favorites.
        /// </summary>
        internal static string CouldNotLoadFavsVerses {
            get {
                return ResourceManager.GetString("CouldNotLoadFavsVerses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find verse for this language at this Id.
        /// </summary>
        internal static string CouldNotVersForId {
            get {
                return ResourceManager.GetString("CouldNotVersForId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not gather verses from selected language.
        /// </summary>
        internal static string CouldNotVersForLang {
            get {
                return ResourceManager.GetString("CouldNotVersForLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorites.
        /// </summary>
        internal static string Favorites {
            get {
                return ResourceManager.GetString("Favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only favorites.
        /// </summary>
        internal static string FavsOnly {
            get {
                return ResourceManager.GetString("FavsOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Havamal.
        /// </summary>
        internal static string FinishedUpdate {
            get {
                return ResourceManager.GetString("FinishedUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Havamal.
        /// </summary>
        internal static string Havamal {
            get {
                return ResourceManager.GetString("Havamal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred inserting new languages.
        /// </summary>
        internal static string InfoLangsInsertFail {
            get {
                return ResourceManager.GetString("InfoLangsInsertFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages updated.
        /// </summary>
        internal static string InfoLangsLoaded {
            get {
                return ResourceManager.GetString("InfoLangsLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred loading Languages.
        /// </summary>
        internal static string InfoLangsLoadedError {
            get {
                return ResourceManager.GetString("InfoLangsLoadedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup of favorites failed.
        /// </summary>
        internal static string InfoSetupFavsFailed {
            get {
                return ResourceManager.GetString("InfoSetupFavsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup of languages failed.
        /// </summary>
        internal static string InfoSetupLangsFailed {
            get {
                return ResourceManager.GetString("InfoSetupLangsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup of stanzas failed.
        /// </summary>
        internal static string InfoSetupVersesFailed {
            get {
                return ResourceManager.GetString("InfoSetupVersesFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred inserting new stanzas.
        /// </summary>
        internal static string InfoVersesInsertFail {
            get {
                return ResourceManager.GetString("InfoVersesInsertFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stanzas updated.
        /// </summary>
        internal static string InfoVersesLoaded {
            get {
                return ResourceManager.GetString("InfoVersesLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured loading stanzas.
        /// </summary>
        internal static string InfoVersesLoadError {
            get {
                return ResourceManager.GetString("InfoVersesLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no favorites.
        /// </summary>
        internal static string NoFavorites {
            get {
                return ResourceManager.GetString("NoFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numeric sort.
        /// </summary>
        internal static string NumSort {
            get {
                return ResourceManager.GetString("NumSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random.
        /// </summary>
        internal static string Random {
            get {
                return ResourceManager.GetString("Random", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetch new.
        /// </summary>
        internal static string RandomBtn {
            get {
                return ResourceManager.GetString("RandomBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search can not be empty.
        /// </summary>
        internal static string SearchEmpty {
            get {
                return ResourceManager.GetString("SearchEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching failed.
        /// </summary>
        internal static string SearchFailed {
            get {
                return ResourceManager.GetString("SearchFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for verses.
        /// </summary>
        internal static string SearchForVerses {
            get {
                return ResourceManager.GetString("SearchForVerses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did not find any verses for search.
        /// </summary>
        internal static string SearchNotFound {
            get {
                return ResourceManager.GetString("SearchNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestaþáttr.
        /// </summary>
        internal static string SectionGas {
            get {
                return ResourceManager.GetString("SectionGas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ljóðatal.
        /// </summary>
        internal static string SectionLjo {
            get {
                return ResourceManager.GetString("SectionLjo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loddfáfnismál.
        /// </summary>
        internal static string SectionLod {
            get {
                return ResourceManager.GetString("SectionLod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rúnatal.
        /// </summary>
        internal static string SectionRun {
            get {
                return ResourceManager.GetString("SectionRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About women.
        /// </summary>
        internal static string SectionWom {
            get {
                return ResourceManager.GetString("SectionWom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Language.
        /// </summary>
        internal static string SelLang {
            get {
                return ResourceManager.GetString("SelLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verses.
        /// </summary>
        internal static string Stanzas {
            get {
                return ResourceManager.GetString("Stanzas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        internal static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Air Theme.
        /// </summary>
        internal static string ThemeAir {
            get {
                return ResourceManager.GetString("ThemeAir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Theme.
        /// </summary>
        internal static string ThemeDark {
            get {
                return ResourceManager.GetString("ThemeDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earth Theme.
        /// </summary>
        internal static string ThemeEarth {
            get {
                return ResourceManager.GetString("ThemeEarth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fire Theme.
        /// </summary>
        internal static string ThemeFire {
            get {
                return ResourceManager.GetString("ThemeFire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Theme.
        /// </summary>
        internal static string ThemeLight {
            get {
                return ResourceManager.GetString("ThemeLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water Theme.
        /// </summary>
        internal static string ThemeWater {
            get {
                return ResourceManager.GetString("ThemeWater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid input not given.
        /// </summary>
        internal static string VerseChoiceError {
            get {
                return ResourceManager.GetString("VerseChoiceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to.
        /// </summary>
        internal static string VerseChoiceOk {
            get {
                return ResourceManager.GetString("VerseChoiceOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select  verse.
        /// </summary>
        internal static string VerseChoicePlace {
            get {
                return ResourceManager.GetString("VerseChoicePlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verse number too high.
        /// </summary>
        internal static string VerseChoiceTooHigh {
            get {
                return ResourceManager.GetString("VerseChoiceTooHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verse number must be higher than 0.
        /// </summary>
        internal static string VerseChoiceTooLow {
            get {
                return ResourceManager.GetString("VerseChoiceTooLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verse version.
        /// </summary>
        internal static string VerseVer {
            get {
                return ResourceManager.GetString("VerseVer", resourceCulture);
            }
        }
    }
}
