name: Xamarin Android Build and Publish

on:
    workflow_dispatch: 

jobs:
  build:
    name: Build and Publish
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Checkout code and Set default Xamarin SDK versions
      run: |
        $VM_ASSETS/select-xamarin-sdk.v2.sh --mono=6.10 --android=10.2

    - name: Set up .NET Core SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '5.0.x'  # Use the appropriate version

    - name: Install Dependencies
      run: dotnet restore

    - name: Build
      run: msbuild 

    - name: Build Android project Havamal/Havamal/Havamal.csproj /t:PackageForAndroid /p:Configuration=Release
      run: msbuild /t:Build /p:Configuration=Release Havamal.sln  # Adjust the solution name


