name: Xamarin Android Build and Publish

on:
    workflow_dispatch: 

jobs:
  build:
    name: Build and Publish
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '5.0.x'  # Use the appropriate version

    - name: Restore NuGet packages
      run: dotnet restore

    - name: List files
      run: ls -R

    - name: Build Android project
      run: msbuild /t:Build /p:Configuration=Release Havamal.sln  # Adjust the solution name

    - name: List files
      run: ls -R

    - name: Publish artifact
      uses: actions/upload-artifact@v2
      with:
        name: app-release
        path: '*.apk'  # Adjust the path to the generated APK

